version: "3.8"

services:
  neo4j:
    image: neo4j:latest
    container_name: neo4j
    volumes:
      - neo4j_storage:/data
    environment:
      - NEO4J_AUTH=neo4j/infraconnexion
      - NEO4JLABS_PLUGINS=["apoc", "graph-data-science"]
      - NEO4J_dbms_security_procedures_unrestricted=apoc.*,gds.*
    ports:
      - "7474:7474"
      - "7687:7687"
volumes:
  neo4j_storage:
